spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/untactedu?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jwt:
    secret: jimin
