spring:
  datasource:
    password: dlcjf2779!
    url: jdbc:mysql://101.101.217.226:3306/untactedu?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jwt:
    secret: jimin
